[package]
name = "move-bytecode-source-map"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
move-binary-format.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-ir-types.workspace = true
move-symbol-pool.workspace = true

bcs.workspace = true

serde.workspace = true

[features]
default = []
