[package]
name = "iota-rpc-loadgen"
version.workspace = true
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
dashmap.workspace = true
dirs.workspace = true
futures.workspace = true
itertools.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
tracing.workspace = true

shellexpand.workspace = true

iota-json-rpc.workspace = true
iota-json-rpc-types.workspace = true
iota-keys.workspace = true
iota-sdk.workspace = true
iota-types = { workspace = true, features = ["test-utils"] }
serde_json.workspace = true
shared-crypto.workspace = true
strum.workspace = true
strum_macros.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
test-cluster.workspace = true

[[bin]]
name = "iota-rpc-loadgen"
path = "src/main.rs"
