[package]
name = "sui-genesis-builder"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
camino.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
rand.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
prometheus.workspace = true

iota-sdk = { version = "1.1.4", default-features = false, features = ["std"] }
packable = { version = "0.8.3", default-features = false }

shared-crypto.workspace = true
sui-config.workspace = true
sui-execution.workspace = true
sui-framework.workspace = true
sui-framework-snapshot.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true
[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }

[[example]]
name = "parse_full_snapshot"
path = "examples/parse_full_snapshot.rs"
