[package]
name = "iota-verifier-v0"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move framework for Iota platform"

[dependencies]
iota-protocol-config.workspace = true
iota-types.workspace = true
move-abstract-interpreter = { path = "../../../external-crates/move/move-execution/v0/crates/move-abstract-interpreter", package = "move-abstract-interpreter-v0" }
move-abstract-stack.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
