[package]
name = "move-bytecode-verifier-v2"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Move bytecode verifier"

[dependencies]
petgraph.workspace = true

move-abstract-interpreter = { path = "../../../v2/crates/move-abstract-interpreter", package = "move-abstract-interpreter-v2" }
move-abstract-stack.workspace = true
move-binary-format.workspace = true
move-borrow-graph.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true

[dev-dependencies]
hex-literal.workspace = true

[features]
default = []
