[package]
name = "iota-macros"
version = "0.7.0"
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
iota-proc-macros.workspace = true
once_cell.workspace = true
futures.workspace = true
tracing.workspace = true
