[package]
name = "narwhal-crypto"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
bcs.workspace = true
fastcrypto.workspace = true
serde.workspace = true
shared-crypto.workspace = true

[features]
default = []

[dev-dependencies]
bincode.workspace = true
hex-literal = "0.4"
serde_json.workspace = true
