[package]
name = "iota-util-mem-derive"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
rust-version = "1.56.1"
description = "Crate for memory reporting"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2.workspace = true
syn.workspace = true
synstructure = "0.12"
