---
apiVersion: v1
kind: Service
metadata:
  name: iota-node
  namespace: rpc-mainnet
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: iota-node
  type: ClusterIP
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-ssd
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: iota-node
  name: iota-node
  namespace: rpc-mainnet
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: iota-node
  serviceName: iota-node
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9184"
        prometheus.io/scrape: "true"
      labels:
        app: iota-node
    spec:
      containers:
        - command:
            - /opt/iota/bin/iota-node
            - --config-path
            - /opt/iota/config/iota-node.yaml
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: info,iota_core=debug,iota_network=debug,narwhal=info,consensus=debug,jsonrpsee=error
          image: x
          imagePullPolicy: Always
          name: iota-node
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            requests:
              cpu: "32"
              memory: 128G
          volumeMounts:
            - mountPath: /opt/iota/db
              name: ssd-storage
            - mountPath: /opt/iota/config/iota-node.yaml
              name: iota-config-volume
              subPath: iota-node.yaml
            - mountPath: /opt/iota/config/genesis.blob
              name: iota-genesis-volume
              subPath: genesis.blob
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      volumes:
        - configMap:
            defaultMode: 420
            name: iota-config
          name: iota-config-volume
        - configMap:
            defaultMode: 420
            name: iota-genesis
          name: iota-genesis-volume
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ssd-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5000Gi
        storageClassName: pd-ssd
        volumeMode: Filesystem
