[package]
name = "iota-bridge"
version.workspace = true
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
ethers = "2.0"
tokio = { workspace = true, features = ["full"] }
iota-types.workspace = true
iota-authority-aggregation.workspace = true
arc-swap.workspace = true
num_enum.workspace = true
move-core-types.workspace = true
url.workspace = true
futures.workspace = true
once_cell.workspace = true
telemetry-subscribers.workspace = true
prometheus.workspace = true
async-trait.workspace = true
typed-store.workspace = true
iota-metrics.workspace = true
iota-sdk.workspace = true
iota-keys.workspace = true
iota-config.workspace = true
clap.workspace = true
tracing.workspace = true
bin-version.workspace = true
bcs.workspace = true
iota-json-rpc-types.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
eyre.workspace = true
tempfile.workspace = true
axum.workspace = true
anyhow.workspace = true
reqwest.workspace = true
fastcrypto.workspace = true
tap.workspace = true
rand.workspace = true
lru.workspace = true
shared-crypto.workspace = true
backoff.workspace = true
enum_dispatch.workspace = true
iota-json-rpc-api.workspace = true
iota-test-transaction-builder.workspace = true

[dev-dependencies]
iota-types = { workspace = true, features = ["test-utils"] }
iota-json-rpc-types = { workspace = true, features = ["test-utils"] }
iota-config.workspace = true
iota-test-transaction-builder.workspace = true
test-cluster.workspace = true
hex-literal = "0.3.4"
maplit = "1.0.2"
