[package]
name = "move-stdlib-natives"
version = "0.1.1"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Diem stdlib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
hex.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
# referred to via path for execution versioning
move-vm-runtime = { path = "../move-vm-runtime" }
move-vm-types.workspace = true
sha2.workspace = true
sha3.workspace = true
smallvec.workspace = true

[features]
default = []
testing = []
