[package]
name = "simulacrum"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait.workspace = true   
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
once_cell.workspace = true
rand.workspace = true
serde.workspace = true
tracing.workspace = true
prometheus.workspace = true
futures.workspace = true

move-bytecode-utils.workspace = true
shared-crypto.workspace = true
iota-config.workspace = true
iota-framework.workspace = true
iota-keys.workspace = true
iota-protocol-config.workspace = true
iota-storage.workspace = true
iota-types.workspace = true
iota-genesis-builder.workspace = true
iota-execution.workspace = true
iota-swarm-config.workspace = true
iota-transaction-checks.workspace = true
