[package]
name = "telemetry-subscribers"
version = "0.2.0"
authors = ["Evan Chan <echan@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false
repository = "https://github.com/mystenlabs/mysten-infra"
description = "Library for common telemetry and observability functionality"

[dependencies]
atomic_float.workspace = true
bytes.workspace = true
bytes-varint = { version = "1" }
clap.workspace = true
console-subscriber = { workspace = true, optional = true }
crossterm.workspace = true
futures.workspace = true
once_cell.workspace = true
opentelemetry = { version = "0.23.0", optional = true }
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"], optional = true }
opentelemetry-otlp = { version = "0.16.0", features = ["grpc-tonic"], optional = true }
opentelemetry-proto = { version = "0.6.0", optional = true }
prometheus.workspace = true
prost.workspace = true
tonic.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-appender.workspace = true
tracing-opentelemetry = { version = "0.24.0", optional = true }
tracing-subscriber.workspace = true

[features]
default = ["otlp"]
tokio-console = ["console-subscriber"]
otlp = [
  "tracing-opentelemetry",
  "opentelemetry",
  "opentelemetry_sdk",
  "opentelemetry-otlp",
  "opentelemetry-proto",
]

[dev-dependencies]
camino.workspace = true
