[package]
name = "telemetry-subscribers"
version = "0.2.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
repository = "https://github.com/mystenlabs/mysten-infra"
description = "Library for common telemetry and observability functionality"

[dependencies]
atomic_float = "1.0"
bytes.workspace = true
bytes-varint = "1.0"
clap.workspace = true
console-subscriber = { version = "0.3", optional = true }
crossterm.workspace = true
futures.workspace = true
once_cell.workspace = true
opentelemetry = "0.23"
opentelemetry-otlp = { version = "0.16", features = ["grpc-tonic"] }
opentelemetry-proto = "0.6"
opentelemetry_sdk = { version = "0.23", features = ["rt-tokio"] }
prometheus.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-appender = "0.2"
tracing-opentelemetry = "0.24"
tracing-subscriber.workspace = true

# must use same version as opentelemetry for tonic and prost, so we can't use from
# workspace
prost = "0.12"
tonic = "0.11"

[features]
default = []
tokio-console = ["console-subscriber"]

[dev-dependencies]
camino.workspace = true
