[package]
name = "telemetry-subscribers"
version = "0.2.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
repository = "https://github.com/mystenlabs/mysten-infra"
description = "Library for common telemetry and observability functionality"

[dependencies]
atomic_float = "1.0"
bytes.workspace = true
bytes-varint = "1.0"
clap.workspace = true
console-subscriber = { version = "0.4", optional = true }
crossterm.workspace = true
futures.workspace = true
once_cell.workspace = true
opentelemetry = "0.24"
opentelemetry-otlp = { version = "0.17", features = ["grpc-tonic"] }
opentelemetry-proto = "0.7"
opentelemetry_sdk = { version = "0.24", features = ["rt-tokio"] }
prometheus.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-appender.workspace = true
tracing-opentelemetry = "0.25"
tracing-subscriber.workspace = true
prost.workspace = true
tonic.workspace = true

[features]
default = []
tokio-console = ["console-subscriber"]

[dev-dependencies]
camino.workspace = true
