[package]
name = "iota-enum-compat-util"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde_yaml.workspace = true
