[package]
name = "iota-proxy"
version = "0.0.2"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-extra.workspace = true
axum-server.workspace = true
bin-version.workspace = true
bytes.workspace = true
clap.workspace = true
const-str.workspace = true
hex.workspace = true
hyper.workspace = true
iota-metrics.workspace = true
iota-tls.workspace = true
iota-types.workspace = true
ipnetwork.workspace = true
itertools.workspace = true
multiaddr.workspace = true
once_cell.workspace = true
prometheus.workspace = true
prost.workspace = true
protobuf.workspace = true
rand.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
snap.workspace = true
tokio = { workspace = true, features = ["full"] }
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true

fastcrypto.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
axum-server.workspace = true
iota-types = { workspace = true, features = ["test-utils"] }
mime.workspace = true
serde_json.workspace = true
tower.workspace = true

[build-dependencies]
prost-build.workspace = true
