[package]
name = "move-binary-format"
version = "0.0.3"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = ["crates-io"]
repository = "https://github.com/diem/diem"
description = "Move Binary Format"

[dependencies]
anyhow.workspace = true
arbitrary = { workspace = true, optional = true, features = ["derive"] }
enum-compat-util.workspace = true
move-core-types.workspace = true
move-proc-macros.workspace = true
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
ref-cast.workspace = true
serde.workspace = true
variant_count.workspace = true

# wasm support (requires js feature of getrandom)
getrandom = { workspace = true, features = ["js"], optional = true }

[dev-dependencies]
move-core-types = { workspace = true, features = ["fuzzing"] }
proptest.workspace = true
proptest-derive.workspace = true

[features]
default = []
fuzzing = [
  "proptest",
  "proptest-derive",
  "arbitrary",
  "move-core-types/fuzzing",
]
wasm = ["getrandom"]

[package.metadata.cargo-udeps.ignore]
normal = ["enum-compat-util"]
