[package]
name = "iota-move-lsp"
version.workspace = true
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

bin-version.workspace = true
move-analyzer.workspace = true

