[package]
name = "sui-core"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
futures.workspace = true
mysten-metrics.workspace = true
parking_lot.workspace = true
prometheus.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tracing.workspace = true

sui-json-rpc-types.workspace = true
sui-types.workspace = true

[dev-dependencies]
bcs.workspace = true
move-core-types.workspace = true
