[package]
name = "narwhal-storage"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["IOTA Foundation <contact@iota.org>"]
publish = false


[dependencies]
tempfile.workspace = true
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
iota-common.workspace = true
iota-metrics.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tracing.workspace = true
types = { path = "../types", package = "narwhal-types" }
store = { path = "../../crates/typed-store", package = "typed-store" }
iota-macros.workspace = true
config = { path = "../config", package = "narwhal-config" }
prometheus.workspace = true
lru.workspace = true
parking_lot.workspace = true
tap.workspace = true

[dev-dependencies]
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }

