[package]
name = "asset_tokenization"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Iota = { local = "../../../../crates/iota-framework/packages/iota-framework" }

[addresses]
asset_tokenization = "0x0"
