validator:
  network-address: /ip4/0.0.0.0/tcp/8080/http
  metrics-address: 0.0.0.0:9184
  json-rpc-address: 0.0.0.0:9000
  admin-interface-port: 1337
  genesis:
    genesis-file-location: /opt/iota/config/genesis.blob
  db-path: /opt/iota/db/authorities_db
  consensus-config:
    db-path: /opt/iota/db/consensus_db
  expensive-safety-check-config:
    enable-epoch-iota-conservation-check: false
    enable-deep-per-tx-iota-conservation-check: false
    force-disable-epoch-iota-conservation-check: false
    enable-state-consistency-check: false
    force-disable-state-consistency-check: false
    enable-move-vm-paranoid-checks: false
  epoch_duration_ms: 120000
