[package]
name = "iota-verifier-latest"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move framework for Iota platform"

[dependencies]
move-abstract-stack.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true

move-abstract-interpreter = { path = "../../../external-crates/move/crates/move-abstract-interpreter" }
move-bytecode-verifier = { path = "../../../external-crates/move/crates/move-bytecode-verifier" }

iota-protocol-config.workspace = true
iota-types.workspace = true
