[package]
name = "move-ir-compiler"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Move IR to bytecode compiler"

[dependencies]
anyhow.workspace = true
clap.workspace = true
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-bytecode-verifier.workspace = true
move-command-line-common.workspace = true
move-ir-to-bytecode.workspace = true
serde_json.workspace = true

bcs.workspace = true

[features]
default = []
