[package]
name = "MainPackage"
version = "0.0.1"

[dependencies]
IOTA = { local = "../../../../crates/iota-framework/packages/iota-framework" }
DepPackage = { local = "../dep_package" }

[addresses]
main_package = "0x0"
