[package]
name = "enum-compat-util"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
serde_yaml.workspace = true
