[package]
name = "move-vm-runtime-v0"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Core Move execution logic"

[dependencies]
better_any.workspace = true
fail.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
sha3.workspace = true
smallvec.workspace = true
tracing.workspace = true

move-binary-format.workspace = true
move-bytecode-verifier = { path = "../move-bytecode-verifier", package = "move-bytecode-verifier-v0" }
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-profiler.workspace = true
move-vm-types.workspace = true

[dev-dependencies]
anyhow.workspace = true
hex.workspace = true
move-compiler.workspace = true
move-ir-compiler.workspace = true
proptest.workspace = true

[features]
default = []
fuzzing = ["move-vm-types/fuzzing"]
failpoints = ["fail/failpoints"]
# Enable tracing and debugging also for release builds. By default, it is only enabled for debug builds.
debugging = []
testing = []
lazy_natives = []
gas-profiler = [
  "move-vm-config/gas-profiler",
  "move-vm-types/gas-profiler",
  "move-vm-profiler/gas-profiler",
]
