[package]
name = "$PACKAGE_NAME"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "$FRAMEWORK_PACKAGES_PATH/move-stdlib" }
Sui = { local = "$FRAMEWORK_PACKAGES_PATH/sui-framework" }
Stardust = { local = "$FRAMEWORK_PACKAGES_PATH/stardust" }

[addresses]
alias = "$ALIAS"