[package]
name = "iota-rosetta"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
axum.workspace = true
axum-extra.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures.workspace = true
once_cell.workspace = true
signature.workspace = true
bcs.workspace = true
hyper.workspace = true
strum.workspace = true
strum_macros.workspace = true
async-trait.workspace = true
clap.workspace = true
thiserror.workspace = true
eyre.workspace = true
typed-store.workspace = true
tempfile.workspace = true
fastcrypto.workspace = true
iota-swarm-config.workspace = true
iota-types.workspace = true
iota-sdk.workspace = true
iota-node.workspace = true
iota-config.workspace = true
iota-keys.workspace = true
iota-json-rpc-types.workspace = true
mysten-metrics.workspace = true
shared-crypto.workspace = true

move-core-types.workspace = true

telemetry-subscribers.workspace = true

[dev-dependencies]
iota-sdk.workspace = true
iota-move-build.workspace = true
test-cluster.workspace = true
tempfile.workspace = true
rand.workspace = true
reqwest.workspace = true
