[package]
name = "iota-transaction-checks"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
once_cell.workspace = true
iota-macros.workspace = true
iota-config.workspace = true
iota-protocol-config.workspace = true
iota-types.workspace = true
tracing.workspace = true
iota-execution.workspace = true
fastcrypto-zkp.workspace = true
