[package]
name = "move-model"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
# diem dependencies
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-symbol-pool.workspace = true

# external dependencies
anyhow.workspace = true
codespan.workspace = true
codespan-reporting.workspace = true
internment.workspace = true
itertools.workspace = true
log.workspace = true
num.workspace = true
once_cell.workspace = true
regex.workspace = true
serde.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
move-prover-test-utils.workspace = true

[[test]]
name = "testsuite"
harness = false
