[package]
name = "bytecode-verifier-libfuzzer"
version = "0.0.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary.workspace = true
libfuzzer-sys.workspace = true
move-binary-format = { workspace = true, features = ["fuzzing"] }
move-bytecode-verifier.workspace = true
move-core-types = { workspace = true, features = ["fuzzing"] }

# Prevent this from interfering with workspaces
# [workspace]
# members = ["."]

[[bin]]
name = "code_unit"
path = "fuzz_targets/code_unit.rs"
test = false
doc = false

[[bin]]
name = "compiled_module"
path = "fuzz_targets/compiled_module.rs"
test = false
doc = false

[[bin]]
name = "mixed"
path = "fuzz_targets/mixed.rs"
test = false
doc = false
