[package]
name = "move-vm-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Types for Move VM"

[dependencies]
proptest = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "rc"] }
smallvec.workspace = true

bcs.workspace = true

move-binary-format.workspace = true
move-core-types.workspace = true
move-vm-profiler.workspace = true

[dev-dependencies]
proptest.workspace = true

[features]
default = []
fuzzing = ["proptest", "move-binary-format/fuzzing"]
gas-profiler = [
  "move-vm-profiler/gas-profiler",
]
