[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bcs = "0.1.6"
clap = { version = "4.5", features = ["derive", "env", "wrap_help"] }
dirs = "5.0.1"
fastcrypto = "0.1.8"
iota-keys = { path = "../../../crates/iota-keys" }
iota-sdk = { path = "../../../crates/iota-sdk" }
iota-types = { path = "../../../crates/iota-types" }
move-core-types = { path = "../../../external-crates/move/crates/move-core-types" }
serde = { version = "1.0.203", features = ["derive"] }
shared-crypto = { path = "../../../crates/shared-crypto" }
tokio = { version = "1.38.0", features = ["time"] }
