[package]
name = "iota-indexer"
version.workspace = true
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bcs.workspace = true
chrono.workspace = true
clap.workspace = true
diesel.workspace = true
diesel-derive-enum.workspace = true
futures.workspace = true
itertools.workspace = true
jsonrpsee.workspace = true
prometheus.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
url.workspace = true

fastcrypto = { workspace = true, features = ["copy_key"] }
iota-json.workspace = true
iota-json-rpc.workspace = true
iota-json-rpc-api.workspace = true
iota-json-rpc-types.workspace = true
iota-open-rpc.workspace = true
iota-package-resolver.workspace = true
iota-protocol-config.workspace = true
iota-rest-api.workspace = true
iota-sdk.workspace = true
iota-transaction-builder.workspace = true
iota-types.workspace = true
mysten-metrics.workspace = true
telemetry-subscribers.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true

cached.workspace = true
diesel_migrations.workspace = true

[features]
pg_integration = []

[dev-dependencies]
criterion.workspace = true
iota-keys.workspace = true
iota-move-build.workspace = true
iota-test-transaction-builder.workspace = true
ntest.workspace = true
simulacrum.workspace = true
test-cluster.workspace = true

[[bin]]
name = "iota-indexer"
path = "src/main.rs"
