[package]
name = "iota-move-build"
version.workspace = true
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Logic for building Iota Move Packages"

[dependencies]
anyhow.workspace = true
fastcrypto.workspace = true
tempfile.workspace = true

iota-verifier = { path = "../../iota-execution/latest/iota-verifier", package = "iota-verifier-latest" }
move-bytecode-verifier = { path = "../../external-crates/move/crates/move-bytecode-verifier" }

iota-protocol-config.workspace = true
iota-types.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-ir-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
