[package]
name = "narwhal-executor"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
async-trait.workspace = true
bcs.workspace = true
bincode.workspace = true
bytes.workspace = true
config = { path = "../config", package = "narwhal-config" }
fastcrypto.workspace = true
futures.workspace = true
iota-protocol-config.workspace = true
primary = { path = "../primary", package = "narwhal-primary" }
prometheus.workspace = true
serde.workspace = true
storage = { path = "../storage", package = "narwhal-storage" }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tonic.workspace = true
tracing.workspace = true

crypto = { path = "../crypto", package = "narwhal-crypto" }
mockall.workspace = true
network = { path = "../network", package = "narwhal-network" }
types = { path = "../types", package = "narwhal-types" }

mysten-metrics.workspace = true
store = { path = "../../crates/typed-store", package = "typed-store" }

[dev-dependencies]
indexmap.workspace = true
node = { path = "../node", package = "narwhal-node" }
primary = { path = "../primary", package = "narwhal-primary" }
telemetry-subscribers.workspace = true
tempfile.workspace = true
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
types = { path = "../types", package = "narwhal-types" }
