[package]
name = "iota-swarm"
version = "0.0.0"
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
rand.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["full"] }
futures.workspace = true
tempfile.workspace = true
tonic-health.workspace = true
tap.workspace = true
prometheus.workspace = true

iota-config.workspace = true
iota-swarm-config.workspace = true
iota-macros.workspace = true
iota-node.workspace = true
iota-protocol-config.workspace = true
iota-types.workspace = true
iota-metrics.workspace = true
iota-network-stack.workspace = true
telemetry-subscribers.workspace = true

[target.'cfg(msim)'.dependencies]
iota-simulator.workspace = true

