[package]
name = "move-transactional-test-runner"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Transactional testing framework for Move"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
once_cell.workspace = true
rayon.workspace = true
regex.workspace = true
tempfile.workspace = true
tokio.workspace = true

move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-cli.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-disassembler.workspace = true
move-ir-compiler.workspace = true
move-ir-types.workspace = true
move-stdlib.workspace = true
move-symbol-pool.workspace = true
move-vm-config.workspace = true
move-vm-runtime.workspace = true
move-vm-test-utils.workspace = true
move-vm-types.workspace = true

[dev-dependencies]
datatest-stable.workspace = true

[[test]]
name = "tests"
harness = false

[features]
failpoints = ['move-vm-runtime/failpoints']
