[package]
name = "iotaop-cli"
version = "0.1.9"
authors = [
  "Jk Jensen <jk@mystenlabs.com>",
  "Mysten Labs <build@mystenlabs.com>",
]
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
name = "iotaoplib"
path = "src/lib.rs"

[[bin]]
name = "iotaop"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
colored.workspace = true
docker-api.workspace = true
field_names.workspace = true
include_dir.workspace = true
inquire.workspace = true
prettytable-rs.workspace = true
regex.workspace = true
reqwest.workspace = true
semver.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
spinners.workspace = true
strum.workspace = true
tokio = { workspace = true, features = ["full"] }
toml_edit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
