[package]
name = "coffee_shop"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }

[addresses]
coffee_shop = "0x0"
