[package]
name = "narwhal-test-utils"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["IOTA Foundation <contact@iota.org>"]
publish = false

[dependencies]
fdlimit.workspace = true
indexmap.workspace = true
itertools.workspace = true
prometheus.workspace = true
rand.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tonic.workspace = true
tracing.workspace = true
once_cell.workspace = true

config = { path = "../config", package = "narwhal-config" }
fastcrypto.workspace = true
crypto = { path = "../crypto", package = "narwhal-crypto" }
executor = { path = "../executor", package = "narwhal-executor" }
network = { path = "../network", package = "narwhal-network" }
node = { path = "../node", package = "narwhal-node" }
primary = { path = "../primary", package = "narwhal-primary" }
types = { path = "../types", package = "narwhal-types" }
worker = { path = "../worker", package = "narwhal-worker" }
storage = { path = "../storage", package = "narwhal-storage" }
iota-metrics.workspace = true
store = { path = "../../crates/typed-store", package = "typed-store" }
telemetry-subscribers.workspace = true
iota-network-stack.workspace = true
iota-protocol-config.workspace = true

anemo.workspace = true
