[package]
name = "mysten-util-mem"
version = "0.11.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/mystenlabs/mysten-infra"
rust-version = "1.56.1"
description = "Collection of memory related utilities"

[dependencies]
cfg-if.workspace = true
ed25519-consensus.workspace = true
fastcrypto = { workspace = true }
fastcrypto-tbls.workspace = true
hashbrown = { version = "0.14", optional = true }
impl-trait-for-tuples = "0.2"
indexmap.workspace = true
lru = { workspace = true, optional = true }
mysten-util-mem-derive.workspace = true
once_cell.workspace = true
parking_lot = { workspace = true, optional = true }
roaring.workspace = true
smallvec = { workspace = true, optional = true }

[features]
default = ["std", "hashbrown", "smallvec", "estimate-heapsize"]
std = ["parking_lot"]
# Full estimate: no call to allocator
estimate-heapsize = []
