[package]
name = "move-package"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Package and build system for Move code"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
itertools.workspace = true
named-lock = "0.4"
once_cell.workspace = true
petgraph.workspace = true
regex.workspace = true
serde.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
tempfile.workspace = true
toml.workspace = true
toml_edit.workspace = true
treeline = "0.1"
walkdir.workspace = true
whoami = "1.5"

move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-docgen.workspace = true
move-model.workspace = true
move-symbol-pool.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
expect-test = "1.5"

[[test]]
name = "test_runner"
harness = false
