[package]
name = "iota-move"
version.workspace = true
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
const-str.workspace = true
git-version.workspace = true
once_cell = { workspace = true, optional = true }
prometheus.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tracing.workspace = true

move-binary-format.workspace = true
move-cli.workspace = true
move-compiler.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-package.workspace = true
move-prover.workspace = true
move-unit-test.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }

move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }

iota-move-build.workspace = true
iota-move-natives = { path = "../../iota-execution/latest/iota-move-natives", package = "iota-move-natives-latest", optional = true }
iota-protocol-config.workspace = true
iota-types.workspace = true

[dev-dependencies]
futures.workspace = true
rand.workspace = true
tempfile.workspace = true

move-package.workspace = true

iota-macros.workspace = true
mysten-metrics.workspace = true

[features]
default = []
build = []
coverage = []
disassemble = []
prove = []
unit_test = ["build", "dep:once_cell", "iota-move-natives"]
calibrate = []
all = ["build", "coverage", "disassemble", "prove", "unit_test", "calibrate"]
