[package]
name = "iota-single-node-benchmark"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
move-package.workspace = true
iota-config.workspace = true
iota-core = { workspace = true, features = ["test-utils"] }
iota-move-build.workspace = true
iota-test-transaction-builder.workspace = true
iota-transaction-checks.workspace = true
iota-types = { workspace = true, features = ["test-utils"] }
iota-storage.workspace = true

async-trait.workspace = true
bcs.workspace = true
clap.workspace = true
fs_extra.workspace = true
futures.workspace = true
prometheus.workspace = true
once_cell.workspace = true
serde = { version = "1.0.190", features = ["derive"] }
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tracing.workspace = true

[dev-dependencies]
iota-macros.workspace = true
iota-protocol-config.workspace = true
iota-simulator.workspace = true
