[package]
name = "iota-single-node-benchmark"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
iota-config.workspace = true
iota-core = { workspace = true, features = ["test-utils"] }
iota-move-build.workspace = true
iota-storage.workspace = true
iota-test-transaction-builder.workspace = true
iota-transaction-checks.workspace = true
iota-types = { workspace = true, features = ["test-utils"] }
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true

async-trait.workspace = true
bcs.workspace = true
clap.workspace = true
fs_extra.workspace = true
futures.workspace = true
once_cell.workspace = true
prometheus.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tracing.workspace = true

[dev-dependencies]
iota-macros.workspace = true
iota-protocol-config.workspace = true
iota-simulator.workspace = true
