[package]
name = "iota-telemetry"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde.workspace = true
reqwest.workspace = true
tracing.workspace = true

iota-core.workspace = true

