[package]
name = "move-stdlib"
version = "0.1.1"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Diem stdlib"

[dependencies]
anyhow.workspace = true
hex.workspace = true
log.workspace = true
move-binary-format.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-docgen.workspace = true
move-errmapgen.workspace = true
move-prover.workspace = true
move-vm-runtime.workspace = true
move-vm-types.workspace = true
sha2.workspace = true
sha3.workspace = true
smallvec.workspace = true
walkdir.workspace = true

[dev-dependencies]
file_diff.workspace = true
move-cli.workspace = true
move-package.workspace = true
move-unit-test.workspace = true
tempfile.workspace = true

[features]
default = []
testing = []
