[package]
name = "iota-genesis-builder"
version = "0.0.0"
authors = ["IOTA Stiftung"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
camino.workspace = true
fastcrypto.workspace = true
hex.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-vm-runtime-v2 = { path = "../../external-crates/move/move-execution/v2/crates/move-vm-runtime" }
rand.workspace = true
rand_regex.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
prometheus.workspace = true

bigdecimal = "0.4.3"
fs_extra = "1.3.0"
iota-sdk = { version = "1.1.4", default-features = false, features = ["irc_27", "irc_30", "std"] }
num-rational = "0.4"
packable = { version = "0.8.3", default-features = false, features = ["io"] }
rand_pcg = "0.3.1"
rand_seeder = "0.2.3"

schemars.workspace = true
shared-crypto.workspace = true
iota-config.workspace = true
iota-execution.workspace = true
iota-adapter-v2 = { path = "../../iota-execution/v2/iota-adapter/" }
iota-framework.workspace = true
iota-framework-snapshot.workspace = true
iota-move-build.workspace = true
iota-move-natives-v2 = { path = "../../iota-execution/v2/iota-move-natives" }
iota-protocol-config.workspace = true
iota-types.workspace = true
[target.'cfg(msim)'.dependencies]
iota-simulator.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true
iota-types = { workspace = true, features = ["test-utils"] }

[[example]]
name = "parse_full_snapshot"
path = "examples/parse_full_snapshot.rs"
