[package]
name = "iota-metric-checker"
version.workspace = true
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
backoff.workspace = true
base64.workspace = true
chrono.workspace = true
clap = { version = "4.3.0", features = ["derive"] }
humantime.workspace = true
once_cell.workspace = true
prometheus-http-query.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_yaml = "0.9.21"
strum_macros.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
