[package]
name = "owned_no_tto"
version = "0.0.1"

[dependencies]
Iota = { git = "https://github.com/iotaledger/kinesis.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/devnet" }
common = { local = "../common" }

[addresses]
owned_no_tto = "0x0"
