[package]
name = "Stardust"
version = "0.0.1"
published-at = "0xda5f"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Sui = { local = "../sui-framework" }

[addresses]
stardust = "0x107a"
