[package]
name = "move-vm-config"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
move-binary-format.workspace = true
once_cell.workspace = true

[features]
gas-profiler = []
