[package]
name = "iota"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anemo.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-kms.workspace = true
bcs.workspace = true
bip32.workspace = true
camino.workspace = true
clap.workspace = true
const-str.workspace = true
datatest-stable.workspace = true
git-version.workspace = true
inquire.workspace = true
insta.workspace = true
json_to_table.workspace = true
miette.workspace = true
prometheus.workspace = true
rand.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
shlex.workspace = true
signature.workspace = true
tabled.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
url.workspace = true

iota-config.workspace = true
iota-execution = { path = "../../iota-execution" }
iota-genesis-builder.workspace = true
iota-json.workspace = true
iota-json-rpc-types.workspace = true
iota-keys.workspace = true
iota-move = { workspace = true, features = ["all"] }
iota-move-build.workspace = true
iota-protocol-config.workspace = true
iota-replay.workspace = true
iota-sdk.workspace = true
iota-source-validation.workspace = true
iota-swarm.workspace = true
iota-swarm-config.workspace = true
iota-transaction-builder.workspace = true
iota-types.workspace = true
move-binary-format.workspace = true
shared-crypto.workspace = true

fastcrypto.workspace = true

colored.workspace = true
rustyline.workspace = true
rustyline-derive.workspace = true
shell-words.workspace = true
unescape.workspace = true

telemetry-subscribers.workspace = true
tempfile.workspace = true

csv.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-vm-profiler.workspace = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemalloc-ctl.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
expect-test.workspace = true
fs_extra.workspace = true
prometheus.workspace = true

iota-macros.workspace = true
iota-simulator.workspace = true
iota-test-transaction-builder.workspace = true
serde_json.workspace = true
test-cluster.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["jemalloc-ctl"]

[[example]]
name = "generate-genesis-checkpoint"
path = "src/generate_genesis_checkpoint.rs"
test = false

[[test]]
name = "ptb_files_tests"
harness = false

[features]
gas-profiler = [
  "iota-types/gas-profiler",
  "iota-execution/gas-profiler",
]
