[package]
name = "iota-transactional-test-runner"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move framework for Iota platform"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bcs.workspace = true
bimap = "0.6"
clap.workspace = true
criterion.workspace = true
eyre.workspace = true
fastcrypto.workspace = true
futures.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
rocksdb.workspace = true
serde_json.workspace = true
simulacrum.workspace = true
telemetry-subscribers.workspace = true
tempfile.workspace = true
tokio.workspace = true
typed-store.workspace = true
typed-store-derive.workspace = true

iota-config.workspace = true
iota-core = { workspace = true, features = ["test-utils"] }
iota-framework.workspace = true
iota-framework-snapshot.workspace = true
iota-graphql-rpc.workspace = true
iota-json-rpc.workspace = true
iota-json-rpc-api.workspace = true
iota-json-rpc-types.workspace = true
iota-protocol-config.workspace = true
iota-rest-api.workspace = true
iota-storage.workspace = true
iota-swarm-config.workspace = true
iota-types = { workspace = true, features = ["test-utils"] }
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-stdlib = { path = "../../external-crates/move/crates/move-stdlib" }
move-symbol-pool.workspace = true
move-transactional-test-runner = { path = "../../external-crates/move/crates/move-transactional-test-runner" }
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }

[target.'cfg(msim)'.dependencies]
msim.workspace = true
