[package]
name = "iota-transactional-test-runner"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for IOTA platform"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
bcs.workspace = true
bimap.workspace = true
clap.workspace = true
eyre.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
tempfile.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde_json.workspace = true
futures.workspace = true
criterion.workspace = true

fastcrypto.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-symbol-pool.workspace = true
move-transactional-test-runner.workspace = true
telemetry-subscribers.workspace = true

move-stdlib = { path = "../../external-crates/move/crates/move-stdlib" }
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }

rocksdb.workspace = true
simulacrum.workspace = true
iota-graphql-rpc.workspace = true
iota-rest-api.workspace = true
iota-swarm-config.workspace = true
iota-config.workspace = true
iota-core = { workspace = true, features = ["test-utils"] }
iota-framework.workspace = true
iota-protocol-config.workspace = true
iota-types = { workspace = true, features = ["test-utils"]}
iota-json-rpc-types.workspace = true
iota-json-rpc.workspace = true
iota-json-rpc-api.workspace = true
iota-framework-snapshot.workspace = true
iota-storage.workspace = true
typed-store.workspace = true
typed-store-derive.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
