[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/iotaledger/iota"
network = "mainnet"
[[packages.values.branches]]
branch = "framework/mainnet"
paths = [
  { path = "crates/iota-framework/packages/deepbook", watch = "0xdee9" },
  { path = "crates/iota-framework/packages/move-stdlib", watch = "0x1" },
  { path = "crates/iota-framework/packages/iota-framework", watch = "0x2" },
  { path = "crates/iota-framework/packages/iota-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/iotaledger/iota"
network = "testnet"
[[packages.values.branches]]
branch = "framework/testnet"
paths = [
  { path = "crates/iota-framework/packages/deepbook", watch = "0xdee9" },
  { path = "crates/iota-framework/packages/move-stdlib", watch = "0x1" },
  { path = "crates/iota-framework/packages/iota-framework", watch = "0x2" },
  { path = "crates/iota-framework/packages/iota-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/iotaledger/iota"
network = "devnet"
[[packages.values.branches]]
branch = "framework/devnet"
paths = [
  { path = "crates/iota-framework/packages/deepbook", watch = "0xdee9" },
  { path = "crates/iota-framework/packages/move-stdlib", watch = "0x1" },
  { path = "crates/iota-framework/packages/iota-framework", watch = "0x2" },
  { path = "crates/iota-framework/packages/iota-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/iotaledger/apps"
network = "mainnet"
[[packages.values.branches]]
branch = "main"
paths = [
  { path = "kiosk" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/iotaledger/apps"
network = "testnet"
[[packages.values.branches]]
branch = "testnet"
paths = [
  { path = "kiosk" },
]

# [[packages]]
# source = "Repository"
# [packages.values]
# repository = "https://github.com/kunalabs-io/iota-smart-contracts"
# [[packages.values.branches]]
# branch = "master"
# paths = [
#   { path = "kai-finance" }
# ]
