[package]
name = "test-generation"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Tool for generating tests for the bytecode verifier and Move VM runtime"

[dependencies]
clap.workspace = true
crossbeam-channel.workspace = true
getrandom.workspace = true
hex.workspace = true
itertools.workspace = true
num_cpus.workspace = true
once_cell.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

module-generation.workspace = true
move-binary-format.workspace = true
move-bytecode-verifier.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-stdlib.workspace = true
move-stdlib-natives.workspace = true
move-vm-runtime.workspace = true
move-vm-test-utils.workspace = true
move-vm-types.workspace = true
