[package]
name = "move-bytecode-viewer"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Explore Move bytecode and how the source code compiles to it"

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm = "0.28"
ratatui.workspace = true
regex.workspace = true

move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-disassembler.workspace = true

[features]
default = []
