[package]
name = "iota-proc-macros"
version = "0.7.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
iota-enum-compat-util.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = { version = "2.0", features = ["full", "fold", "extra-traits"] }

[target.'cfg(msim)'.dependencies]
msim-macros.workspace = true
