[package]
name = "move-vm-test-utils"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move VM Test Utils"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
once_cell.workspace = true
serde.workspace = true

move-binary-format.workspace = true
move-core-types.workspace = true
move-vm-profiler.workspace = true
move-vm-types.workspace = true

[features]
default = []
tiered-gas = []
gas-profiler = []
