[package]
name = "iota-upgrade-compatibility-transactional-tests"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Transactional tests for package upgrade compatibility checking"

[dev-dependencies]
anyhow.workspace = true
datatest-stable.workspace = true
insta.workspace = true
iota-move-build.workspace = true
move-binary-format.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-package.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]
