[package]
name = "move-proc-macros"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
proc-macro = true

[dependencies]
enum-compat-util.workspace = true
quote.workspace = true
syn = { version = "2", features = ["full", "fold", "extra-traits"] }
