[package]
name = "iota-json-rpc"
version = "0.0.0"
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
arc-swap.workspace = true
chrono.workspace = true
fastcrypto.workspace = true
jsonrpsee.workspace = true
hyper.workspace = true
http-body = "0.4"
itertools.workspace = true
indexmap.workspace = true
tower.workspace = true
axum.workspace = true
tower-http.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-bytecode-utils.workspace = true
prometheus.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
serde.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
signature.workspace = true
thiserror.workspace = true
bcs.workspace = true
eyre.workspace = true
once_cell.workspace = true
serde_json.workspace = true

tap.workspace = true

iota-core.workspace = true
iota-storage.workspace = true
iota-types.workspace = true
iota-json.workspace = true
iota-json-rpc-api.workspace = true
iota-open-rpc.workspace = true
iota-open-rpc-macros.workspace = true
iota-protocol-config.workspace = true
iota-config.workspace = true
iota-json-rpc-types.workspace = true
iota-macros.workspace = true
iota-transaction-builder.workspace = true
iota-metrics.workspace = true
iota-service.workspace = true
shared-crypto.workspace = true
typed-store-error.workspace = true
cached.workspace = true

[dev-dependencies]
mockall.workspace = true
expect-test.workspace = true
iota-types = { workspace = true, features = ["test-utils"] }
telemetry-subscribers.workspace = true
