[package]
name = "bytecode-verifier-tests-v0"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move bytecode verifier tests"

[dev-dependencies]
hex.workspace = true
petgraph.workspace = true

move-abstract-interpreter.workspace = true
move-binary-format = { workspace = true, features = ["fuzzing"] }
# referred to via path for execution versioning
move-bytecode-verifier = { path = "../move-bytecode-verifier", package = "move-bytecode-verifier-v0" }
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true

[features]
fuzzing = ["move-binary-format/fuzzing"]
