name: TS End-to-end Tests

on:
  workflow_call:
    inputs:
      isRust:
        type: boolean
        required: true
      isExplorer:
        type: boolean
        required: true
      isTypescriptSDK:
        type: boolean
        required: true
      isWallet:
        type: boolean
        required: true
      isGraphQlTransport:
        type: boolean
        required: true

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Run e2e test against localnet built on the develop branch
  localnet:
    name: Localnet
    if: inputs.isExplorer || inputs.isTypescriptSDK || inputs.isWallet || inputs.isRust
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: iota_indexer_v2
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0
      - run: cargo build --bin iota --features indexer --profile dev
      - name: Install Nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm --filter iota-explorer playwright install --with-deps chromium

      - name: Set env
        run: |
          echo "VITE_IOTA_BIN=$PWD/target/debug/iota" >> $GITHUB_ENV
          echo "E2E_RUN_LOCAL_NET_CMD=(RUST_LOG=info RUST_BACKTRACE=1 $(echo $PWD/target/debug/iota) start --with-indexer --pg-port 5432 --pg-db-name iota_indexer_v2 --with-graphql=127.0.0.1:9125)" >> $GITHUB_ENV

      - name: Run TS SDK e2e tests
        if: inputs.isTypescriptSDK || inputs.isRust
        run: pnpm dlx concurrently --kill-others --success command-1 "$E2E_RUN_LOCAL_NET_CMD" 'pnpm --filter @iota/iota-sdk test:e2e'

      - name: Run RPC/GraphQL compatibility e2e tests
        if: inputs.isGraphQlTransport || inputs.isRust
        run: pnpm dlx concurrently --kill-others --success command-1 "$E2E_RUN_LOCAL_NET_CMD" 'pnpm --filter @iota/graphql-transport test:e2e'

      - name: Build explorer
        if: inputs.isTypescriptSDK || inputs.isExplorer || inputs.isRust
        run: pnpm turbo --filter=iota-explorer build

      - name: Run Explorer e2e tests
        if: inputs.isTypescriptSDK || inputs.isExplorer || inputs.isRust
        run: pnpm --filter iota-explorer playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-explorer
          path: apps/explorer/playwright-report/
          retention-days: 30

      - name: Run Local net
        run: cargo run --bin iota start --force-regenesis --with-faucet --epoch-duration-ms 10000 &

      - name: Build Wallet
        if: inputs.isWallet || inputs.isRust || inputs.isTypescriptSDK
        run: pnpm wallet build

      - name: Run Wallet e2e tests
        if: inputs.isWallet || inputs.isRust || inputs.isTypescriptSDK
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm --filter iota-wallet playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-wallet
          path: apps/wallet/playwright-report/
          retention-days: 30
