name: Rust lints

on: workflow_call

jobs:
  rustfmt:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      - name: Install latest nightly
        run: rustup toolchain install nightly --component rustfmt --allow-downgrade
      - name: Check Rust formatting
        run: |
          cargo +nightly ci-fmt-external

  cargo-deny:
    name: cargo-deny (advisories, licenses, bans, ...)
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      - uses: EmbarkStudios/cargo-deny-action@v1

  clippy:
    needs:
      - rustfmt
      - cargo-deny
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      - run: rustup component add clippy

      # See '.cargo/config' for list of enabled/disabled clippy lints
      - name: cargo move-clippy
        run: |
          cargo ci-clippy-external
