name: Move tests

on: workflow_call

concurrency:
  group: move-tests-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  # This job ensures that Move unit tests are run if there are changes
  # to Move code but not Rust code (If there are Rust changes, they
  # will be run as part of a larger test suite).
  move-test:
    timeout-minutes: 10
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      - uses: taiki-e/install-action@nextest
      - name: Run move tests
        run: |
          cargo nextest run -p iota-framework-tests -- unit_tests::
