name: Preview Deploy for Apps UI Kit Storybook

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.APPS_UI_KIT_VERCEL_PROJECT_ID }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "apps/ui-kit/**"
      - "apps/ui-icons/**"
      - ".github/workflows/apps-ui-kit-preview.deploy.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    permissions:
      contents: read
      pull-requests: write
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0
      - name: Install Nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install Vercel CLI
        run: pnpm add --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --cwd ./apps/ui-kit --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --cwd ./apps/ui-kit --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --cwd ./apps/ui-kit --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > vercel_output.txt
      - name: Extract Deploy URL
        id: deploy_url
        run: echo "DEPLOY_URL=$(cat vercel_output.txt | awk 'END{print}')" >> $GITHUB_OUTPUT
      - name: Comment on pull request
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const DEPLOY_URL = '${{ steps.deploy_url.outputs.DEPLOY_URL }}'
            const COMMIT_SHA = '${{ github.event.pull_request.head.sha }}'
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `This pull request has been deployed to Vercel.\n\n\nLatest commit: ${COMMIT_SHA}\n\n:white_check_mark: Preview: ${DEPLOY_URL}`
            })
