name: Docs spellcheck and linting

on:
  push:
    branches: [develop, extensions]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  diff:
    runs-on: [self-hosted]
    outputs:
      isDoc: ${{ steps.diff.outputs.isDoc }}
      isOldDoc: ${{ steps.diff.outputs.isOldDoc }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      - name: Detect Changes
        uses: "./.github/actions/diffs"
        id: diff

  spelling:
    name: Lint documentation
    needs: diff
    if: needs.diff.outputs.isDoc == 'true'
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      - name: Spell Check Docs
        uses: crate-ci/typos@v1.16.11
        with:
          files: ./docs/content
