name: Update the Fastcrypto pointer IOTA

on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:
  schedule:
    # Update on every hour at 10 past the hour
    - cron: "10 * * * *"

jobs:
  update-dep:
    runs-on: self-hosted
    # Important settings as we don't want to open a PR when the update fails
    continue-on-error: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
      # Fork of 'Swatinem/rust-cache' which allows caching additional paths
      - uses: bmwill/rust-cache@fb63fcd7a959767755b88b5af2f5cbf65fb8a127 # pin@v1
      - name: Install cargo-hakari, and cache the binary
        uses: baptiste0928/cargo-install@1cd874a5478fdca35d868ccc74640c5aabbb8f1b # pin@v3.0.0
        with:
          crate: cargo-hakari
          locked: true
      - name: Update the fastcrypto pointer
        run: |
          scripts/update_fastcrypto.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # pin@v5
        with:
          # TODO: change the token to something FC-specific?
          token: ${{ secrets.NW_AUTO_UPDATE }}
          commit-message: chore(deps) Update the Fastcrypto pointer
          title: chore(deps) Update the Fastcrypto pointer
          body: |
            - Update Fastcrypto

            Auto-generated by [create-pull-request][1] and the scripts/update_fastcrypto.sh script

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-fastcrypto
