name: Links Checker

on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:

  ## Run this workflow automatically every week
  schedule:
    - cron: "0 0 * * *"

jobs:
  links-checker:
    name: Check links and create automated issue if needed
    runs-on: self-hosted
    env:
      LYCHEE_OUT: ./lychee/links-report
    steps:
      ## Check out code using Git
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4

      - name: Check all links at *.md and doc files
        id: lychee
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # pin@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: ${{ env.LYCHEE_OUT }}
          format: markdown
          ## Do not fail this step on broken links
          fail: false
          ## Allow pages replying with 200 (Ok)in at most 20 seconds
          ## This checks all md files in the repo
          args: >-
            --verbose
            --accept 200
            --timeout 20
            --max-concurrency 10
            --no-progress
            './**/*.md'

      - name: Find the last report issue open
        uses: micalevisk/last-issue-action@305829d9728f47beb0029417167a0af890edfd6e # pin@v2.1
        id: last_issue
        with:
          state: open
          labels: broken-links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update report
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # pin@v4
        with:
          title: Link checker report
          content-filepath: ${{ env.LYCHEE_OUT }}
          issue-number: ${{ steps.last_issue.outputs.issue_number }}
          labels: broken-links

      - name: Close last report open issue
        if: steps.lychee.outputs.exit_code == 0
        uses: peter-evans/close-issue@276d7966e389d888f011539a86c8920025ea0626 # pin@v3
        with:
          issue-number: ${{ steps.last_issue.outputs.issue_number }}
