name: Tag

on:
  repository_dispatch:
    types: [tag-main]

  workflow_call:
    inputs:
      iota_commit:
        description: "IOTA repo commit to tag"
        type: string
        required: true
      tag_name:
        description: "Tag Name"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      iota_commit:
        description: "IOTA repo commit to tag"
        type: string
        required: true
      tag_name:
        description: "Tag Name"
        type: string
        required: true

env:
  IOTA_COMMIT: "${{ github.event.client_payload.iota_commit || inputs.iota_commit }}"
  TAG_NAME: "${{ github.event.client_payload.tag_name || inputs.tag_name }}"

jobs:
  tag:
    name: Tag
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4

      - name: Tag
        uses: julbme/gh-action-manage-tag@8daf6387badea2c6b8f989bd0f82b5a9ef1d84e6 # pin@v1
        with:
          name: ${{ env.TAG_NAME }}
          state: present
          from: ${{ env.IOTA_COMMIT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
