[package]
name = "move-command-line-common"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Move shared command line and file tools"

[dependencies]
anyhow.workspace = true
colored.workspace = true
dirs-next.workspace = true
hex.workspace = true
num-bigint.workspace = true
once_cell.workspace = true
serde.workspace = true
sha2.workspace = true
similar.workspace = true
vfs.workspace = true
walkdir.workspace = true

move-core-types.workspace = true

[dev-dependencies]
proptest.workspace = true
