[package]
name = "docs-examples"
version.workspace = true
edition = "2021"

[dependencies]
anyhow.workspace = true
tokio.workspace = true

bcs.workspace = true
iota-keys.workspace = true
iota-sdk.workspace = true
move-core-types.workspace = true
shared-crypto.workspace = true

[[example]]
name = "nft-output-claim"
path = "stardust/nft-output-claim.rs"

[[example]]
name = "alias-output-claim"
path = "stardust/alias-output-claim.rs"
