[package]
name = "docs-examples"
version.workspace = true
authors = ["IOTA Stiftung"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dev-dependencies]
anyhow.workspace = true
bcs.workspace = true
bip32.workspace = true
serde_json.workspace = true
tokio.workspace = true

iota-keys.workspace = true
iota-move-build.workspace = true
iota-sdk.workspace = true
move-core-types.workspace = true
shared-crypto.workspace = true

[[example]]
name = "address_unlock_condition"
path = "stardust/address_unlock_condition.rs"

[[example]]
name = "nft-output-claim"
path = "stardust/nft-output-claim.rs"

[[example]]
name = "alias-output-claim"
path = "stardust/alias-output-claim.rs"

[[example]]
name = "basic-output-claim"
path = "stardust/basic-output-claim.rs"

[[example]]
name = "check-basic-output-unlock-conditions"
path = "stardust/check-basic-output-unlock-conditions.rs"

[[example]]
name = "nft-migration"
path = "stardust/nft-migration.rs"

[[example]]
name = "foundry-output-claim"
path = "stardust/foundry-output-claim.rs"
